import type { Player } from "@/types";

export const mockPlayers: Player[] = [
  {
    id: "player-bukayo-saka",
    name: "Bukayo Saka",
    slug: "bukayo-saka",
    sport: "FOOTBALL",
    teamId: "team-arsenal",
    position: "Winger",
    nationality: "England",
    photoUrl: "/players/bukayo-saka.jpg",
    jerseyNumber: 7,
  },
  {
    id: "player-declan-rice",
    name: "Declan Rice",
    slug: "declan-rice",
    sport: "FOOTBALL",
    teamId: "team-arsenal",
    position: "Midfielder",
    nationality: "England",
    photoUrl: "/players/declan-rice.jpg",
    jerseyNumber: 41,
  },
  {
    id: "player-cole-palmer",
    name: "Cole Palmer",
    slug: "cole-palmer",
    sport: "FOOTBALL",
    teamId: "team-chelsea",
    position: "Attacking Midfielder",
    nationality: "England",
    photoUrl: "/players/cole-palmer.jpg",
    jerseyNumber: 20,
  },
  {
    id: "player-erling-haaland",
    name: "Erling Haaland",
    slug: "erling-haaland",
    sport: "FOOTBALL",
    teamId: "team-man-city",
    position: "Striker",
    nationality: "Norway",
    photoUrl: "/players/erling-haaland.jpg",
    jerseyNumber: 9,
  },
  {
    id: "player-mohamed-salah",
    name: "Mohamed Salah",
    slug: "mohamed-salah",
    sport: "FOOTBALL",
    teamId: "team-liverpool",
    position: "Forward",
    nationality: "Egypt",
    photoUrl: "/players/mohamed-salah.jpg",
    jerseyNumber: 11,
  },
  {
    id: "player-jude-bellingham",
    name: "Jude Bellingham",
    slug: "jude-bellingham",
    sport: "FOOTBALL",
    teamId: "team-real-madrid",
    position: "Midfielder",
    nationality: "England",
    photoUrl: "/players/jude-bellingham.jpg",
    jerseyNumber: 5,
  },
  {
    id: "player-kylian-mbappe",
    name: "Kylian Mbappé",
    slug: "kylian-mbappe",
    sport: "FOOTBALL",
    teamId: "team-real-madrid",
    position: "Forward",
    nationality: "France",
    photoUrl: "/players/kylian-mbappe.jpg",
    jerseyNumber: 9,
  },
  {
    id: "player-lamine-yamal",
    name: "Lamine Yamal",
    slug: "lamine-yamal",
    sport: "FOOTBALL",
    teamId: "team-barcelona",
    position: "Winger",
    nationality: "Spain",
    photoUrl: "/players/lamine-yamal.jpg",
    jerseyNumber: 19,
  },
  {
    id: "player-harry-kane",
    name: "Harry Kane",
    slug: "harry-kane",
    sport: "FOOTBALL",
    teamId: "team-bayern-munich",
    position: "Striker",
    nationality: "England",
    photoUrl: "/players/harry-kane.jpg",
    jerseyNumber: 9,
  },
  {
    id: "player-ousmane-dembele",
    name: "Ousmane Dembélé",
    slug: "ousmane-dembele",
    sport: "FOOTBALL",
    teamId: "team-psg",
    position: "Forward",
    nationality: "France",
    photoUrl: "/players/ousmane-dembele.jpg",
    jerseyNumber: 10,
  },

  // NBA
  {
    id: "player-lebron-james",
    name: "LeBron James",
    slug: "lebron-james",
    sport: "NBA",
    teamId: "team-lakers",
    position: "Forward",
    nationality: "USA",
    photoUrl: "/players/lebron-james.jpg",
    jerseyNumber: 23,
  },
  {
    id: "player-anthony-davis",
    name: "Anthony Davis",
    slug: "anthony-davis",
    sport: "NBA",
    teamId: "team-lakers",
    position: "Forward-Center",
    nationality: "USA",
    photoUrl: "/players/anthony-davis.jpg",
    jerseyNumber: 3,
  },
  {
    id: "player-jayson-tatum",
    name: "Jayson Tatum",
    slug: "jayson-tatum",
    sport: "NBA",
    teamId: "team-celtics",
    position: "Forward",
    nationality: "USA",
    photoUrl: "/players/jayson-tatum.jpg",
    jerseyNumber: 0,
  },
  {
    id: "player-jaylen-brown",
    name: "Jaylen Brown",
    slug: "jaylen-brown",
    sport: "NBA",
    teamId: "team-celtics",
    position: "Guard-Forward",
    nationality: "USA",
    photoUrl: "/players/jaylen-brown.jpg",
    jerseyNumber: 7,
  },
  {
    id: "player-stephen-curry",
    name: "Stephen Curry",
    slug: "stephen-curry",
    sport: "NBA",
    teamId: "team-warriors",
    position: "Guard",
    nationality: "USA",
    photoUrl: "/players/stephen-curry.jpg",
    jerseyNumber: 30,
  },
  {
    id: "player-jalen-brunson",
    name: "Jalen Brunson",
    slug: "jalen-brunson",
    sport: "NBA",
    teamId: "team-knicks",
    position: "Guard",
    nationality: "USA",
    photoUrl: "/players/jalen-brunson.jpg",
    jerseyNumber: 11,
  },
  {
    id: "player-giannis-antetokounmpo",
    name: "Giannis Antetokounmpo",
    slug: "giannis-antetokounmpo",
    sport: "NBA",
    teamId: "team-bucks",
    position: "Forward",
    nationality: "Greece",
    photoUrl: "/players/giannis-antetokounmpo.jpg",
    jerseyNumber: 34,
  },
  {
    id: "player-nikola-jokic",
    name: "Nikola Jokić",
    slug: "nikola-jokic",
    sport: "NBA",
    teamId: "team-nuggets",
    position: "Center",
    nationality: "Serbia",
    photoUrl: "/players/nikola-jokic.jpg",
    jerseyNumber: 15,
  },
];

export function getMockPlayerBySlug(slug: string): Player | undefined {
  return mockPlayers.find((p) => p.slug === slug);
}

export function getMockPlayersByTeam(teamId: string): Player[] {
  return mockPlayers.filter((p) => p.teamId === teamId);
}
