import type { Team } from "@/types";

/**
 * Featured teams have full detail (colors, founding year, city) for team
 * profile pages. Additional teams exist so league standings/fixtures look
 * like a real, populated table rather than 4 rows.
 */
export const mockTeams: Team[] = [
  // Premier League
  {
    id: "team-arsenal",
    name: "Arsenal",
    slug: "arsenal",
    shortName: "ARS",
    sport: "FOOTBALL",
    leagueId: "league-premier-league",
    logoUrl: "/teams/arsenal.svg",
    city: "London",
    foundedYear: 1886,
    colorPrimary: "#EF0107",
    colorSecondary: "#FFFFFF",
  },
  {
    id: "team-chelsea",
    name: "Chelsea",
    slug: "chelsea",
    shortName: "CHE",
    sport: "FOOTBALL",
    leagueId: "league-premier-league",
    logoUrl: "/teams/chelsea.svg",
    city: "London",
    foundedYear: 1905,
    colorPrimary: "#034694",
    colorSecondary: "#FFFFFF",
  },
  {
    id: "team-man-city",
    name: "Manchester City",
    slug: "manchester-city",
    shortName: "MCI",
    sport: "FOOTBALL",
    leagueId: "league-premier-league",
    logoUrl: "/teams/manchester-city.svg",
    city: "Manchester",
    foundedYear: 1880,
    colorPrimary: "#6CABDD",
    colorSecondary: "#1C2C5B",
  },
  {
    id: "team-liverpool",
    name: "Liverpool",
    slug: "liverpool",
    shortName: "LIV",
    sport: "FOOTBALL",
    leagueId: "league-premier-league",
    logoUrl: "/teams/liverpool.svg",
    city: "Liverpool",
    foundedYear: 1892,
    colorPrimary: "#C8102E",
    colorSecondary: "#F6EB61",
  },
  {
    id: "team-man-united",
    name: "Manchester United",
    slug: "manchester-united",
    shortName: "MUN",
    sport: "FOOTBALL",
    leagueId: "league-premier-league",
    logoUrl: "/teams/manchester-united.svg",
    city: "Manchester",
    foundedYear: 1878,
    colorPrimary: "#DA291C",
    colorSecondary: "#FBE122",
  },
  {
    id: "team-tottenham",
    name: "Tottenham Hotspur",
    slug: "tottenham-hotspur",
    shortName: "TOT",
    sport: "FOOTBALL",
    leagueId: "league-premier-league",
    logoUrl: "/teams/tottenham.svg",
    city: "London",
    foundedYear: 1882,
  },
  {
    id: "team-newcastle",
    name: "Newcastle United",
    slug: "newcastle-united",
    shortName: "NEW",
    sport: "FOOTBALL",
    leagueId: "league-premier-league",
    logoUrl: "/teams/newcastle.svg",
    city: "Newcastle",
  },
  {
    id: "team-aston-villa",
    name: "Aston Villa",
    slug: "aston-villa",
    shortName: "AVL",
    sport: "FOOTBALL",
    leagueId: "league-premier-league",
    logoUrl: "/teams/aston-villa.svg",
    city: "Birmingham",
  },
  {
    id: "team-brighton",
    name: "Brighton & Hove Albion",
    slug: "brighton",
    shortName: "BHA",
    sport: "FOOTBALL",
    leagueId: "league-premier-league",
    logoUrl: "/teams/brighton.svg",
    city: "Brighton",
  },
  {
    id: "team-west-ham",
    name: "West Ham United",
    slug: "west-ham",
    shortName: "WHU",
    sport: "FOOTBALL",
    leagueId: "league-premier-league",
    logoUrl: "/teams/west-ham.svg",
    city: "London",
  },

  // La Liga
  {
    id: "team-real-madrid",
    name: "Real Madrid",
    slug: "real-madrid",
    shortName: "RMA",
    sport: "FOOTBALL",
    leagueId: "league-la-liga",
    logoUrl: "/teams/real-madrid.svg",
    city: "Madrid",
    foundedYear: 1902,
    colorPrimary: "#FEBE10",
    colorSecondary: "#00529F",
  },
  {
    id: "team-barcelona",
    name: "Barcelona",
    slug: "barcelona",
    shortName: "BAR",
    sport: "FOOTBALL",
    leagueId: "league-la-liga",
    logoUrl: "/teams/barcelona.svg",
    city: "Barcelona",
    foundedYear: 1899,
    colorPrimary: "#A50044",
    colorSecondary: "#004D98",
  },
  {
    id: "team-atletico-madrid",
    name: "Atlético Madrid",
    slug: "atletico-madrid",
    shortName: "ATM",
    sport: "FOOTBALL",
    leagueId: "league-la-liga",
    logoUrl: "/teams/atletico-madrid.svg",
    city: "Madrid",
  },
  {
    id: "team-sevilla",
    name: "Sevilla",
    slug: "sevilla",
    shortName: "SEV",
    sport: "FOOTBALL",
    leagueId: "league-la-liga",
    logoUrl: "/teams/sevilla.svg",
    city: "Seville",
  },

  // Serie A
  {
    id: "team-juventus",
    name: "Juventus",
    slug: "juventus",
    shortName: "JUV",
    sport: "FOOTBALL",
    leagueId: "league-serie-a",
    logoUrl: "/teams/juventus.svg",
    city: "Turin",
  },
  {
    id: "team-inter-milan",
    name: "Inter Milan",
    slug: "inter-milan",
    shortName: "INT",
    sport: "FOOTBALL",
    leagueId: "league-serie-a",
    logoUrl: "/teams/inter-milan.svg",
    city: "Milan",
  },
  {
    id: "team-ac-milan",
    name: "AC Milan",
    slug: "ac-milan",
    shortName: "MIL",
    sport: "FOOTBALL",
    leagueId: "league-serie-a",
    logoUrl: "/teams/ac-milan.svg",
    city: "Milan",
  },
  {
    id: "team-napoli",
    name: "Napoli",
    slug: "napoli",
    shortName: "NAP",
    sport: "FOOTBALL",
    leagueId: "league-serie-a",
    logoUrl: "/teams/napoli.svg",
    city: "Naples",
  },

  // Bundesliga
  {
    id: "team-bayern-munich",
    name: "Bayern Munich",
    slug: "bayern-munich",
    shortName: "BAY",
    sport: "FOOTBALL",
    leagueId: "league-bundesliga",
    logoUrl: "/teams/bayern-munich.svg",
    city: "Munich",
    foundedYear: 1900,
    colorPrimary: "#DC052D",
    colorSecondary: "#0066B2",
  },
  {
    id: "team-dortmund",
    name: "Borussia Dortmund",
    slug: "borussia-dortmund",
    shortName: "BVB",
    sport: "FOOTBALL",
    leagueId: "league-bundesliga",
    logoUrl: "/teams/borussia-dortmund.svg",
    city: "Dortmund",
  },
  {
    id: "team-leipzig",
    name: "RB Leipzig",
    slug: "rb-leipzig",
    shortName: "RBL",
    sport: "FOOTBALL",
    leagueId: "league-bundesliga",
    logoUrl: "/teams/rb-leipzig.svg",
    city: "Leipzig",
  },

  // Ligue 1
  {
    id: "team-psg",
    name: "Paris Saint-Germain",
    slug: "psg",
    shortName: "PSG",
    sport: "FOOTBALL",
    leagueId: "league-ligue-1",
    logoUrl: "/teams/psg.svg",
    city: "Paris",
    foundedYear: 1970,
    colorPrimary: "#004170",
    colorSecondary: "#DA291C",
  },

  // NBA
  {
    id: "team-lakers",
    name: "Los Angeles Lakers",
    slug: "lakers",
    shortName: "LAL",
    sport: "NBA",
    leagueId: "league-nba",
    logoUrl: "/teams/lakers.svg",
    city: "Los Angeles",
    foundedYear: 1947,
    colorPrimary: "#552583",
    colorSecondary: "#FDB927",
  },
  {
    id: "team-celtics",
    name: "Boston Celtics",
    slug: "celtics",
    shortName: "BOS",
    sport: "NBA",
    leagueId: "league-nba",
    logoUrl: "/teams/celtics.svg",
    city: "Boston",
    foundedYear: 1946,
    colorPrimary: "#007A33",
    colorSecondary: "#BA9653",
  },
  {
    id: "team-warriors",
    name: "Golden State Warriors",
    slug: "warriors",
    shortName: "GSW",
    sport: "NBA",
    leagueId: "league-nba",
    logoUrl: "/teams/warriors.svg",
    city: "San Francisco",
    foundedYear: 1946,
    colorPrimary: "#1D428A",
    colorSecondary: "#FFC72C",
  },
  {
    id: "team-knicks",
    name: "New York Knicks",
    slug: "knicks",
    shortName: "NYK",
    sport: "NBA",
    leagueId: "league-nba",
    logoUrl: "/teams/knicks.svg",
    city: "New York",
    foundedYear: 1946,
    colorPrimary: "#006BB6",
    colorSecondary: "#F58426",
  },
  {
    id: "team-bucks",
    name: "Milwaukee Bucks",
    slug: "bucks",
    shortName: "MIL",
    sport: "NBA",
    leagueId: "league-nba",
    logoUrl: "/teams/bucks.svg",
    city: "Milwaukee",
    foundedYear: 1968,
    colorPrimary: "#00471B",
    colorSecondary: "#EEE1C6",
  },
  {
    id: "team-nuggets",
    name: "Denver Nuggets",
    slug: "nuggets",
    shortName: "DEN",
    sport: "NBA",
    leagueId: "league-nba",
    logoUrl: "/teams/nuggets.svg",
    city: "Denver",
    foundedYear: 1967,
    colorPrimary: "#0E2240",
    colorSecondary: "#FEC524",
  },
  {
    id: "team-76ers",
    name: "Philadelphia 76ers",
    slug: "76ers",
    shortName: "PHI",
    sport: "NBA",
    leagueId: "league-nba",
    logoUrl: "/teams/76ers.svg",
    city: "Philadelphia",
  },
  {
    id: "team-suns",
    name: "Phoenix Suns",
    slug: "suns",
    shortName: "PHX",
    sport: "NBA",
    leagueId: "league-nba",
    logoUrl: "/teams/suns.svg",
    city: "Phoenix",
  },
  {
    id: "team-mavericks",
    name: "Dallas Mavericks",
    slug: "mavericks",
    shortName: "DAL",
    sport: "NBA",
    leagueId: "league-nba",
    logoUrl: "/teams/mavericks.svg",
    city: "Dallas",
  },
  {
    id: "team-timberwolves",
    name: "Minnesota Timberwolves",
    slug: "timberwolves",
    shortName: "MIN",
    sport: "NBA",
    leagueId: "league-nba",
    logoUrl: "/teams/timberwolves.svg",
    city: "Minneapolis",
  },
];

export function getMockTeamBySlug(slug: string): Team | undefined {
  return mockTeams.find((t) => t.slug === slug);
}

export function getMockTeamsBySport(sport: Team["sport"]): Team[] {
  return mockTeams.filter((t) => t.sport === sport);
}

export function getMockTeamsByLeague(leagueId: string): Team[] {
  return mockTeams.filter((t) => t.leagueId === leagueId);
}
